import type { Segment } from "./Segment";
import { LanePattern as L } from "../types/LanePattern";
import { SegmentTypes as T } from "../types/SegmentType";

export const SEGMENT_ROW_BODY_LENGHT = 0.9;
export const SEGMENT_ROW_SPACING_LENGHT = 1.8;

export const SEGMENT_ROW_LENGTH =
    SEGMENT_ROW_BODY_LENGHT + SEGMENT_ROW_SPACING_LENGHT;

export const SEGMENTS: Segment[] = [
    {
        id: "baseFifty1",
        type: T.Scenario,
        weight: 3,
        canReversed: true,
    
        pattern: [
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.JumpCoins],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "baseFifty2",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.EnemyCar, L.EnemyCar, L.EnemyCar],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Booster, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
            [L.Obstacle, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
            [L.Obstacle, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "baseFifty3",
        type: T.Scenario,
        weight: 1,
        canReversed: true,
    
        pattern: [
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "baseFifty4",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Empty],
            [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Empty],
            [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Empty],
            [L.Empty, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Coin, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
            [L.Empty, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "trafficShort",
        type: T.Scenario,
        weight: 8,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.EnemyCar, L.EnemyCar, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.EnemyCar, L.EnemyCar, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "trafficLong1",
        type: T.Scenario,
        weight: 6,
        canReversed: true,
    
        pattern: [
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.EnemyCar],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.BulletItem],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.EnemyCar],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.EnemyCar, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Coin, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Jump, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.EnemyCar, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "trafficLong2",
        type: T.Scenario,
        weight: 4,
        canReversed: true,
    
        pattern: [
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.EnemyCar],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
            [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
            [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "gettingBullet",
        type: T.Quick,
        weight: 2,
        canReversed: false,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "gettingBooster",
        type: T.Quick,
        weight: 3,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Booster, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "sheltedBooster1",
        type: T.Quick,
        weight: 3,
        canReversed: false,
    
        pattern: [
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Obstacle, L.Coin],
            [L.Coin, L.Obstacle, L.Booster, L.Obstacle, L.Coin],
            [L.Coin, L.Obstacle, L.Empty, L.Obstacle, L.Coin],
            [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "sheltedBooster2",
        type: T.Quick,
        weight: 2,
        canReversed: false,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.BulletItem],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
            [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
            [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
            [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "sheltedCoin1",
        type: T.Scenario,
        weight: 3,
        canReversed: true,
    
        pattern: [
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.EnemyCar, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.EnemyCar],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.EnemyCar, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.EnemyCar, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Empty, L.Empty, L.EnemyCar],
            [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "sheltedCoin2",
        type: T.Scenario,
        weight: 3,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Booster, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "jumpers1",
        type: T.Scenario,
        weight: 5,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Booster, L.Empty, L.Coin, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.EnemyCar, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "jumpers2",
        type: T.Scenario,
        weight: 4,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.JumpCoins, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.JumpCoins],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.JumpCoins, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty]
        ],
    },
    {
        id: "jumpers3",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.JumpCoins],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "jumpers4",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Jump, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Jump, L.Empty],
            [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Jump, L.Empty, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Jump, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Nitro, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Jump, L.Empty, L.Obstacle],
            [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "jumpers5",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Jump, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Jump, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Jump, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Jump],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Shield, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Nitro, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Jump, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "movingBlocks1",
        type: T.Scenario,
        weight: 2,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.MovingObstacle],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
            [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Booster, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "movingBlocks2",
        type: T.Scenario,
        weight: 4,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Shield, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.MovingObstacle, L.Empty, L.Booster, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
    {
        id: "shots1",
        type: T.Scenario,
        weight: 4,
        canReversed: true,
    
        pattern: [
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
            [L.Shield, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
            [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty]
        ],
    },
];
