import type { Segment } from "./Segment";
import { LanePattern as L } from "../types/LanePattern";
import { SegmentTypes as T } from "../types/SegmentType";

export const EASY_SEGMENTS: Segment[] = [
  {
    id: "easyWarmupCoins",
    type: T.Scenario,
    weight: 5,
    canReversed: true,
    difficulty: 1,
    pattern: [
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Coin, L.Empty, L.Empty, L.Empty],
      [L.Coin, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
  {
    id: "easyGateLeftRight",
    type: T.Scenario,
    weight: 4,
    canReversed: true,
    difficulty: 1,
    pattern: [
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Obstacle1, L.Empty, L.Empty],
      [L.Empty, L.Obstacle1, L.Empty, L.Empty],
      [L.Coin, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Obstacle1, L.Empty],
      [L.Empty, L.Empty, L.Obstacle1, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
  {
    id: "easyWideSlalom",
    type: T.Scenario,
    weight: 4,
    canReversed: true,
    difficulty: 2,
    pattern: [
      [L.Coin, L.Empty, L.Empty, L.Obstacle1],
      [L.Coin, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Obstacle1],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Obstacle1, L.Empty, L.Empty, L.Coin],
      [L.Empty, L.Empty, L.Empty, L.Coin],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
  {
    id: "easyBoosterPocket",
    type: T.Scenario,
    weight: 2,
    canReversed: true,
    difficulty: 2,
    pattern: [
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Obstacle1, L.Empty, L.Booster, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
  {
    id: "easyJumpLine",
    type: T.Scenario,
    weight: 2,
    canReversed: true,
    difficulty: 3,
    pattern: [
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.JumpCoins, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Obstacle1, L.Empty, L.Empty, L.Obstacle1],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
  {
    id: "easyTrafficIntro",
    type: T.Scenario,
    weight: 2,
    canReversed: true,
    difficulty: 3,
    pattern: [
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Coin, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.EnemyCar],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Coin, L.Empty],
      [L.EnemyCar, L.Empty, L.Coin, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
      [L.Empty, L.Empty, L.Empty, L.Empty],
    ],
  },
];
