import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const BASE_SEGMENTS: Segment[] = [
  {
      id: "baseFifty1",
      type: T.Scenario,
      weight: 3,
      canReversed: true,
      difficulty: 2,
  
      pattern: [
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.JumpCoins],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "baseFifty2",
      type: T.Scenario,
      weight: 2,
      canReversed: true,
      difficulty: 3,
  
      pattern: [
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.EnemyCar, L.EnemyCar, L.EnemyCar],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Booster, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
        [L.Obstacle, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
        [L.Obstacle, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "baseFifty3",
      type: T.Scenario,
      weight: 1,
      canReversed: true,
      difficulty: 4,
  
      pattern: [
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "baseFifty4",
      type: T.Scenario,
      weight: 2,
      canReversed: true,
      difficulty: 4,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Obstacle, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Empty],
        [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Empty],
        [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Empty],
        [L.Empty, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Coin, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
        [L.Empty, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
