import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const HAZARD_SEGMENTS: Segment[] = [
  {
      id: "movingBlocks1",
      type: T.Scenario,
      weight: 2,
      canReversed: true,
      difficulty: 6,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.MovingObstacle],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Booster, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "movingBlocks2",
      type: T.Scenario,
      weight: 3,
      canReversed: true,
      difficulty: 7,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.MovingObstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Shield, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.MovingObstacle, L.Empty, L.Booster, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "shots1",
      type: T.Scenario,
      weight: 4,
      canReversed: true,
      difficulty: 3,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Shield, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
