import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const JUMPER_SEGMENTS: Segment[] = [
  {
      id: "jumpers1",
      type: T.Scenario,
      weight: 5,
      canReversed: true,
      difficulty: 5,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Booster, L.Empty, L.Coin, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.EnemyCar, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "jumpers2",
      type: T.Scenario,
      weight: 4,
      canReversed: true,
      difficulty: 7,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.JumpCoins, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.JumpCoins],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.JumpCoins, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
      ],
    },
  {
      id: "jumpers3",
      type: T.Scenario,
      weight: 2,
      canReversed: true,
      difficulty: 4,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.JumpCoins],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.EnemyCar, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.JumpCoins, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "jumpers4",
      type: T.Scenario,
      weight: 1,
      canReversed: true,
      difficulty: 9,
  
      pattern: [
        [L.Empty, L.Empty, L.Jump, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Jump, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Jump, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Jump, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Nitro, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Jump, L.Empty, L.Obstacle],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "jumpers5",
      type: T.Scenario,
      weight: 2,
      canReversed: true,
      difficulty: 10,
  
      pattern: [
        [L.Jump, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Jump, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Jump, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Jump],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Shield, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Nitro, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Jump, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
