import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const REWARD_SEGMENTS: Segment[] = [
  {
      id: "gettingBullet",
      type: T.Quick,
      weight: 2,
      canReversed: false,
      difficulty: 1,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "gettingBooster",
      type: T.Quick,
      weight: 3,
      canReversed: true,
      difficulty: 1,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Booster, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "sheltedBooster1",
      type: T.Quick,
      weight: 3,
      canReversed: false,
      difficulty: 4,
  
      pattern: [
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Obstacle, L.Coin],
        [L.Coin, L.Obstacle, L.Booster, L.Obstacle, L.Coin],
        [L.Coin, L.Obstacle, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "sheltedBooster2",
      type: T.Quick,
      weight: 2,
      canReversed: false,
      difficulty: 5,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.BulletItem],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Obstacle, L.Obstacle, L.Empty],
        [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
        [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
        [L.Empty, L.Obstacle, L.Booster, L.Obstacle, L.Empty],
        [L.Empty, L.Obstacle, L.Empty, L.Obstacle, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "sheltedCoin1",
      type: T.Scenario,
      weight: 3,
      canReversed: true,
      difficulty: 5,
  
      pattern: [
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.EnemyCar, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.EnemyCar],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.EnemyCar, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.EnemyCar, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "sheltedCoin2",
      type: T.Scenario,
      weight: 3,
      canReversed: true,
      difficulty: 5,
  
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Obstacle, L.Empty, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Coin, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Obstacle, L.Empty],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Booster, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Coin, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Empty, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
