import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const TRAFFIC_SEGMENTS: Segment[] = [
  {
      id: "trafficShort",
      type: T.Scenario,
      weight: 8,
      canReversed: true,
      difficulty: 4,
  
      pattern: [
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.EnemyCar, L.EnemyCar, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.EnemyCar, L.EnemyCar, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "trafficLong1",
      type: T.Scenario,
      weight: 6,
      canReversed: true,
      difficulty: 6,
  
      pattern: [
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.EnemyCar],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.BulletItem],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.EnemyCar],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.EnemyCar, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Coin, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Jump, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.EnemyCar, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "trafficLong2",
      type: T.Scenario,
      weight: 4,
      canReversed: true,
      difficulty: 7,
  
      pattern: [
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.EnemyCar],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
        [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Obstacle],
        [L.Coin, L.Empty, L.Empty, L.Obstacle, L.Obstacle],
        [L.Coin, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.EnemyCar, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Empty, L.Obstacle, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Obstacle, L.Obstacle],
        [L.EnemyCar, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.EnemyCar],
        [L.Obstacle, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Coin],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.EnemyCar, L.Empty],
        [L.Obstacle, L.Obstacle, L.Obstacle, L.Empty, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Obstacle, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.EnemyCar],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
