import type { Segment } from "../Segment";
import { LanePattern as L } from "../../types/LanePattern";
import { SegmentTypes as T } from "../../types/SegmentType";

export const VERTICAL_SEGMENTS: Segment[] = [
  {
      id: "overpassCenterHigh",
      type: T.Scenario,
      weight: 8,
      canReversed: false,
      difficulty: 1,
      elevatedSections: [
        {
          lanes: [1, 2, 3],
          rowStart: 2,
          rowEnd: 18,
          height: 5.2,
          rampRows: 4,
          rampIn: true,
          rampOut: false,
        },
      ],
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Empty, L.Booster, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Coin, L.Empty],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.EnemyCar, L.Empty, L.Empty, L.Empty, L.EnemyCar],
        [L.Empty, L.Coin, L.Nitro, L.Coin, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.BulletItem, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Coin, L.Empty],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "overpassSplitHigh",
      type: T.Scenario,
      weight: 6,
      canReversed: true,
      difficulty: 2,
      elevatedSections: [
        {
          lanes: [0, 1],
          rowStart: 1,
          rowEnd: 15,
          height: 4.4,
          rampRows: 3,
          rampIn: true,
          rampOut: false,
        },
        {
          lanes: [3, 4],
          rowStart: 6,
          rowEnd: 20,
          height: 5.6,
          rampRows: 4,
          rampIn: true,
          rampOut: false,
        },
      ],
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Booster, L.Obstacle, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Coin],
        [L.Obstacle, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Obstacle, L.Booster, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Coin, L.Empty, L.Empty, L.Coin, L.Empty],
        [L.Coin, L.Empty, L.Obstacle, L.Coin, L.Empty],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Coin, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Coin, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    },
  {
      id: "overUnderVerticalSplit",
      type: T.Scenario,
      weight: 7,
      canReversed: true,
      difficulty: 3,
      elevatedSections: [
        {
          lanes: [0, 1],
          rowStart: 2,
          rowEnd: 18,
          height: 5.4,
          rampRows: 4,
          rampIn: true,
          rampOut: false,
        },
        {
          lanes: [3, 4],
          rowStart: 2,
          rowEnd: 18,
          height: 5.4,
          rampRows: 4,
          rampIn: true,
          rampOut: false,
        },
        {
          lanes: [2],
          rowStart: 4,
          rowEnd: 20,
          height: -3.4,
          rampRows: 5,
          rampIn: false,
          rampOut: true,
        },
      ],
      pattern: [
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Coin, L.Coin, L.Empty, L.Coin, L.Coin],
        [L.Coin, L.Empty, L.Empty, L.Empty, L.Coin],
        [L.Empty, L.Booster, L.Coin, L.Booster, L.Empty],
        [L.Obstacle, L.Empty, L.Coin, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.Empty, L.Empty, L.Magnet, L.Empty, L.Empty],
        [L.Coin, L.Empty, L.Coin, L.Empty, L.Coin],
        [L.Coin, L.Obstacle, L.Empty, L.Obstacle, L.Coin],
        [L.Empty, L.Empty, L.Coin, L.Empty, L.Empty],
        [L.Empty, L.Coin, L.Coin, L.Coin, L.Empty],
        [L.Obstacle, L.Empty, L.BulletItem, L.Empty, L.Obstacle],
        [L.Empty, L.Coin, L.Empty, L.Coin, L.Empty],
        [L.Coin, L.Empty, L.Coin, L.Empty, L.Coin],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.JumpCoins, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
        [L.Empty, L.Empty, L.Empty, L.Empty, L.Empty],
      ],
    }
];
