import type { LevelConfig } from "@/levels/types";

const volcanicIsland = {
  id: "volcanic_island",
  name: "Volcanic Island",
  description:
    "Red-hot island route with lava glow, smoky fog and sharp volcanic silhouettes.",
  enabled: false,
  to_show: true,
  difficultyIds: ["normal", "hard"],

  visual: {
    camera: {
      distance: 25,
      height: 20,
      fov: 60,
      fovMax: 102,
      tilt: 0.3,
      lookahead: 20,
      followSpeed: 0.7,
      distanceReductionFactor: 0.8,
    },

    render: {
      backgroundColor: "#1B0908",
      fogColor: "#2A0D0A",
      fogNear: 0.01,
      fogFar: 150,
      toneMappingExposure: 0.92,
      bloomStrength: 0.3,
      bloomRadius: 0.5,
      bloomThreshold: 1.2,
    },

    lighting: {
      ambientLightColor: "#3A1410",
      ambientLightIntensity: 0.35,
      directionalLightColor: "#FFB06A",
      directionalLightPosition: [-12, 22, -6],
      directionalLightIntensity: 1.25,
      fillLightColor: "#FF4A2E",
      fillLightPosition: [8, 10, 10],
      fillLightIntensity: 1.9,
      backAccentLightColor: "#FF2A16",
      backAccentLightPosition: [0, 4, 18],
      backAccentLightIntensity: 6.2,
    },
  },

  environment: {
    road: {
      color: "#201313",
      emissiveColor: "#FF3A22",
      emissiveIntensity: 0.18,
      opacity: 0.34,
      laneColor: "#ffa587",
      length: 800,
      edges: {
        color: "#FF2A16",
        height: 10,
        opacity: 0,
      },
      sideObjects: {
        enabled: true,
        color: "#3A1B16",
        emissiveColor: "#FF3A22",
        emissiveIntensity: 1.0,
        opacity: 1,
        spacing: 4,
        offset: 0.6,
        y: 0.4,
        scale: [1.75, 1.4, 1.75],
      },
    },

    scenery: {
      scenerySets: ["volcanic"],
      sceneryDensity: 1.05,
      decorations: ["lava_flow", "basalt", "ash_cloud", "volcano"],
      layers: [
        {
          type: "terrain_surface",
          xMin: -360,
          xMax: 360,
          zStart: -340,
          zEnd: 70,
          spacing: 1,
          speedFactor: 0.035,
          minHeight: 1,
          maxHeight: 1,
          minWidth: 1,
          maxWidth: 1,
          y: -5.6,
          color: "#130C0B",
          secondaryColor: "#2A1110",
          emissiveColor: "#3A100B",
          emissiveIntensity: 0.08,
          opacity: 0.9,
          waveAmplitude: 0.18,
          waveFrequency: 0.035,
          waveSpeed: 0.28,
        },
        {
          type: "terrain_surface",
          xMin: -335,
          xMax: -48,
          zStart: -310,
          zEnd: 45,
          spacing: 1,
          speedFactor: 0.05,
          minHeight: 1,
          maxHeight: 1,
          minWidth: 1,
          maxWidth: 1,
          y: -7.2,
          color: "#1B100E",
          secondaryColor: "#2A1511",
          emissiveColor: "#3A100B",
          emissiveIntensity: 0.05,
          opacity: 0.74,
          waveAmplitude: 2.8,
          waveFrequency: 0.026,
          waveSpeed: 0.18,
        },
        {
          type: "terrain_surface",
          xMin: 48,
          xMax: 335,
          zStart: -310,
          zEnd: 45,
          spacing: 1,
          speedFactor: 0.05,
          minHeight: 1,
          maxHeight: 1,
          minWidth: 1,
          maxWidth: 1,
          y: -7.35,
          color: "#1A0D0C",
          secondaryColor: "#301410",
          emissiveColor: "#3A100B",
          emissiveIntensity: 0.05,
          opacity: 0.74,
          waveAmplitude: 2.6,
          waveFrequency: 0.025,
          waveSpeed: 0.17,
        },
        {
          type: "lava_flow",
          xMin: -245,
          xMax: -86,
          zStart: -310,
          zEnd: 50,
          spacing: 42,
          speedFactor: 0.055,
          minHeight: 0.05,
          maxHeight: 0.09,
          minWidth: 4.5,
          maxWidth: 9.5,
          y: -4.72,
          color: "#FF531F",
          emissiveColor: "#FF2A16",
          emissiveIntensity: 2.4,
          opacity: 0.72,
        },
        {
          type: "lava_flow",
          xMin: 92,
          xMax: 255,
          zStart: -330,
          zEnd: 55,
          spacing: 46,
          speedFactor: 0.052,
          minHeight: 0.05,
          maxHeight: 0.09,
          minWidth: 3.8,
          maxWidth: 8.5,
          y: -4.7,
          color: "#FF7A22",
          emissiveColor: "#FF3719",
          emissiveIntensity: 2.1,
          opacity: 0.66,
        },
        {
          type: "terrain_surface",
          xMin: -330,
          xMax: 330,
          zStart: -280,
          zEnd: 15,
          spacing: 1,
          speedFactor: 0.035,
          minHeight: 1,
          maxHeight: 1,
          minWidth: 1,
          maxWidth: 1,
          y: -18,
          color: "#120C0B",
          secondaryColor: "#23110F",
          emissiveColor: "#3C0B08",
          emissiveIntensity: 0.04,
          opacity: 0.42,
          waveAmplitude: 10,
          waveFrequency: 0.012,
          waveSpeed: 0.06,
        },
      ],
    },

    weather: {
      sky: {
        enabled: true,
        topColor: "#14080A",
        bottomColor: "#33100B",
        cloudColor: "#5C2118",
        opacity: 0.82,
        noiseStrength: 0.44,
        noiseScale: 4.2,
        speed: 0.035,
      },
      fireRocks: {
        enabled: true,
        count: 42,
        color: "#FF5A1F",
        coreColor: "#FFD38A",
        opacity: 0.72,
        areaWidth: 155,
        areaDepth: 170,
        minHeight: 38,
        maxHeight: 118,
        minFallSpeed: 18,
        maxFallSpeed: 44,
        windX: -7,
        windZ: 10,
        minSize: 0.55,
        maxSize: 1.65,
      },
      lightning: {
        enabled: true,
        color: "#ff8d8d",
        minInterval: 2.2,
        maxInterval: 5.8,
        duration: 0.36,
        intensity: 10.5,
        position: [-40, 125, -180],
      },
    },
  },

  interactive: {
    coinSets: ["default"],
    boosterSets: ["default"],
    obstacleSets: ["storm"],
    jumpSets: ["default"],
    segmentSets: ["base", "traffic", "rewards", "jumpers", "hazards"],
    density: 1.0,
    obstacleDensity: 1.15,
  },

  player: {
    carSet: "default",
    effectSet: "default",
    visual: {
      defaultEmissionIntensity: 5,
      defaultBlinkDuration: 1,
      defaultBlinkSpeed: 11,
      emissiveColors: {
        default: "#000000",
        nitro: "#FF4A16",
        shield: "#FFB06A",
        damage: "#FF0000",
      },
      nitroTrail: {
        color: "#ff4a16",
        width: 2.4,
        height: 0.9,
        offsetX: 0.85,
        offsetY: 0.25,
        offsetZ: 2,
        timeScale: 4.4,
      },
    },
  },

  music: {
    gameTrack: "music_background",
  },

  rewards: {
    coins: 175,
  },
} satisfies LevelConfig;

export default volcanicIsland;
