import type { LevelConfig } from "@/levels/types";

const volcanicIsland = {
  id: "volcanic_island",
  name: "Volcanic Island",
  description: "Red-hot island route with lava glow, smoky fog and sharp volcanic silhouettes.",

  visual: {
    camera: {
      distance: 25,
      height: 20,
      fov: 60,
      fovMax: 102,
      tilt: 0.3,
      lookahead: 20,
      followSpeed: 0.7,
      distanceReductionFactor: 0.8,
    },

    render: {
      backgroundColor: "#1B0908",
      fogColor: "#2A0D0A",
      fogNear: 0.01,
      fogFar: 185,
      toneMappingExposure: 0.92,
      bloomStrength: 1.35,
      bloomRadius: 0.1,
      bloomThreshold: 0.95,
    },

    lighting: {
      ambientLightColor: "#3A1410",
      ambientLightIntensity: 0.35,
      directionalLightColor: "#FFB06A",
      directionalLightPosition: [-12, 22, -6],
      directionalLightIntensity: 1.25,
      fillLightColor: "#FF4A2E",
      fillLightPosition: [8, 10, 10],
      fillLightIntensity: 1.9,
      backAccentLightColor: "#FF2A16",
      backAccentLightPosition: [0, 4, 18],
      backAccentLightIntensity: 6.2,
    },
  },

  environment: {
    road: {
      color: "#201313",
      emissiveColor: "#FF3A22",
      emissiveIntensity: 0.18,
      opacity: 0.34,
      laneColor: "#FF5A24",
      length: 800,
      edges: {
        color: "#FF2A16",
        height: 10,
        opacity: 0,
      },
      sideObjects: {
        enabled: true,
        color: "#3A1B16",
        emissiveColor: "#FF3A22",
        emissiveIntensity: 0.55,
        opacity: 1,
        spacing: 4,
        offset: 0.6,
        y: 0.4,
        scale: [1.75, 1.4, 1.75],
      },
    },

    scenery: {
      scenerySets: ["volcanic"],
      sceneryDensity: 1.05,
      decorations: ["lava_flow", "basalt", "ash_cloud", "volcano"],
      layers: [
        {
          type: "water_surface",
          xMin: -360,
          xMax: 360,
          zStart: -340,
          zEnd: 70,
          spacing: 1,
          speedFactor: 0.055,
          minHeight: 1,
          maxHeight: 1,
          minWidth: 1,
          maxWidth: 1,
          y: -5.2,
          color: "#250806",
          secondaryColor: "#FF4D19",
          emissiveColor: "#FF2A16",
          emissiveIntensity: 0.55,
          opacity: 0.78,
          waveAmplitude: 0.8,
          waveFrequency: 0.055,
          waveSpeed: 0.9,
        },
        {
          type: "hills",
          xMin: -230,
          xMax: -78,
          zStart: -230,
          zEnd: 35,
          spacing: 16,
          speedFactor: 0.08,
          minHeight: 18,
          maxHeight: 46,
          minWidth: 28,
          maxWidth: 74,
          y: -22,
          color: "#2B1714",
          emissiveColor: "#FF3A22",
          emissiveIntensity: 0.1,
          opacity: 0.94,
        },
        {
          type: "hills",
          xMin: 78,
          xMax: 230,
          zStart: -230,
          zEnd: 35,
          spacing: 16,
          speedFactor: 0.08,
          minHeight: 18,
          maxHeight: 46,
          minWidth: 28,
          maxWidth: 74,
          y: -22,
          color: "#321A14",
          emissiveColor: "#FF3A22",
          emissiveIntensity: 0.1,
          opacity: 0.94,
        },
        {
          type: "hills",
          xMin: -330,
          xMax: 330,
          zStart: -280,
          zEnd: 15,
          spacing: 34,
          speedFactor: 0.035,
          minHeight: 42,
          maxHeight: 86,
          minWidth: 62,
          maxWidth: 130,
          y: -48,
          color: "#1F1110",
          emissiveColor: "#FF2A16",
          emissiveIntensity: 0.06,
          opacity: 0.58,
        },
      ],
    },
  },

  interactive: {
    coinSets: ["default"],
    boosterSets: ["default"],
    obstacleSets: ["storm"],
    jumpSets: ["default"],
    density: 1.0,
    obstacleDensity: 1.15,
  },

  player: {
    carSet: "default",
    effectSet: "default",
    visual: {
      defaultEmissionIntensity: 5,
      defaultBlinkDuration: 1,
      defaultBlinkSpeed: 11,
      emissiveColors: {
        default: "#000000",
        nitro: "#FF4A16",
        shield: "#FFB06A",
        damage: "#FF0000",
      },
      nitroTrail: {
        color: "#ff4a16",
        width: 2.4,
        height: 0.9,
        offsetX: 0.85,
        offsetY: 0.25,
        offsetZ: 2,
        timeScale: 4.4,
      },
    },
  },

  music: {
    gameTrack: "music_background",
  },

  rewards: {
    coins: 175,
  },
} satisfies LevelConfig;

export default volcanicIsland;
